apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauth-token-cleaner
  namespace: openshift-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oauth-token-cleaner
rules:
  - apiGroups:
      - oauth.openshift.io
    resources:
      - oauthaccesstokens
    verbs:
      - get
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oauth-token-cleaner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oauth-token-cleaner
subjects:
  - kind: ServiceAccount
    name: oauth-token-cleaner
    namespace: openshift-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: oauth-token-cleaner
  namespace: openshift-config
spec:
  schedule: "0 */12 * * *"   # a cada 12h
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          serviceAccountName: oauth-token-cleaner
          restartPolicy: Never
          containers:
            - name: cleaner
              image: registry.redhat.io/openshift4/ose-cli:latest
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - -ceu
                - |
                  set -euo pipefail

                  TODAY="$(date -u +%Y-%m-%d)"
                  echo "[INFO] Iniciando limpeza de OAuthAccessTokens (UTC=$TODAY)"

                  # Lista tokens (nome + campos úteis), remove os de HOJE e os que contêm "console"
                  # Depois extrai só o 1º campo (nome do token) e deleta um a um
                  TOKENS=$(
                    oc get oauthaccesstokens -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.userName}{"\t"}{.redirectURI}{"\t"}{.metadata.creationTimestamp}{"\n"}{end}' \
                      | egrep -v "${TODAY}|console" \
                      | awk '{print $1}' \
                      || true
                  )

                  if [[ -z "${TOKENS}" ]]; then
                    echo "[INFO] Tokens candidatos à remoção: 0"
                    echo "[INFO] Nenhum token para remover. Encerrando."
                    exit 0
                  fi

                  COUNT=$(echo "${TOKENS}" | wc -l | tr -d ' ')
                  echo "[INFO] Tokens candidatos à remoção: ${COUNT}"

                  while IFS= read -r token; do
                    [[ -z "$token" ]] && continue
                    echo "[INFO] Deletando token: $token"
                    oc delete oauthaccesstoken "$token" --ignore-not-found
                  done <<< "${TOKENS}"

                  echo "[INFO] Limpeza concluída"
